main: jar.essem.main.Main
name: KoradoxLevels
version: 1.0

author: EssemDotJar
description: Levels plugin for Koradox.

api-version: 1.19

commands:
  level:
    usage: /level
    description: WhatIsMyLevel...
  giveitem:
    usage: /give <onlinePlayer> <item> [amount]
  openfurnace:
    usage: /openfurnace
  setcooktime:
    usage: /setcooktime <ticks>